abuild.in: make is_x_package functions reliant on being given a name
alpinelinux/abuild pull request #67
Opened 2019-04-28 22:06 UTC by maxice8

@5paceToast

2019-04-28 22:34 UTC, CosmicToast requested changes

2019-04-28 22:34 UTC, 5paceToast commented on abuild.in
> +	elif [ "${subpkgarch:-$pkgarch}" != "noarch" ] && ! is_dev_pkg "$name"; then
`archcheck()` does not define `$name` like `postcheck()` does.
```suggestion
	elif [ "${subpkgarch:-$pkgarch}" != "noarch" ] && ! is_dev_pkg "$subpkgname"; then
```

2019-04-28 23:57 UTC, CosmicToast approved these changes

2019-04-29 18:40 UTC, ncopa commented
can you please rebase?

2019-04-29 18:56 UTC, maxice8 commented
rebased

2019-04-29 21:26 UTC, closed without merging