Fix condition check for adding static libraries to -dev package.
alpinelinux/abuild pull request #72
Opened 2019-05-01 08:03 UTC by maxice8

This was the wrong way, we only want to add the static library to the
-dev package when there isn't a -static package.

2019-05-01 08:17 UTC, maxice8 commented
@ncopa without this, it is required to declare $pkgname-static before $pkgname-dev, otherwise $pkgname-dev will mv the static library to itself and $pkgname-static will fail

2019-05-01 14:09 UTC, tcely commented on abuild.in
> +			$([ "${subpackages##*$pkgname-static*}" ] && find $libdirs \
Please use `-n` instead.

2019-05-01 14:14 UTC, tcely requested changes

2019-05-01 14:14 UTC, tcely commented on abuild.in
> +			$([ "${subpackages##*$pkgname-static*}" ] && find $libdirs \
```suggestion
			$([ -n "${subpackages##*$pkgname-static*}" ] && find $libdirs \
```

2019-05-04 22:48 UTC, tcely commented on abuild.in
> +			$([ -n "${subpackages##*$pkgname-static*}" ] && find $libdirs \
```suggestion
			$(! subpackage_types_has  static && find $libdirs \
```

2019-05-04 23:04 UTC, maxice8 commented on abuild.in
> +			$([ -n "${subpackages##*$pkgname-static*}" ] && find $libdirs \
applied.

2019-05-04 23:49 UTC, tcely commented
See also https://github.com/alpinelinux/abuild/pull/66

2019-05-05 09:46 UTC, tcely commented on abuild.in
> +			$([ -n "${subpackages##*$pkgname-static*}" ] && find $libdirs \
Where was this applied?

2019-05-05 20:18 UTC, tcely commented on abuild.in
> +			$([subpackage_types_has static || find $libdirs \
```suggestion
			$(subpackage_types_has static || find $libdirs \
```

2019-05-05 22:09 UTC, maxice8 commented on abuild.in
> +			$([subpackage_types_has static || find $libdirs \
fixed, thanks

2019-05-05 22:29 UTC, tcely commented on abuild.in
> +			$([subpackage_types_has static || find $libdirs \
You're welcome

2019-06-12 19:00 UTC, maxice8 commented
@ncopa can we get this merged ? it is causing minor annoyances to people that want to make $pkgname-static subpackages

2019-06-12 19:29 UTC, tcely approved these changes

2019-07-06 07:15 UTC, sergey-safarov commented
Yes, I also stuck with improper static files packaging when `-static` defined after `-dev` package.

2019-07-06 07:17 UTC, maxice8 commented
@ncopa

2019-07-08 11:30 UTC, closed without merging