Fix git repo ssh
alpinelinux/abuild pull request #89
Opened 2019-05-23 22:37 UTC by pdietl

2019-05-26 21:21 UTC, tcely approved these changes

2019-06-25 01:13 UTC, pdietl commented
ping @tcely @ncopa 

Is this good to go? :)

2019-07-08 17:38 UTC, tcely commented
:ping_pong: @ncopa

2019-07-17 12:39 UTC, tcely commented on functions.sh.in
> +			*/aports | */aports.git) APORTSDIR=$gitbase ;;
```suggestion
			*/aports|*/aports.git) APORTSDIR=$gitbase ;;
```

I'm not sure if the spaces are going to affect the match or not, but better to just not have them.

2019-07-17 12:45 UTC, tcely commented on functions.sh.in
>  			case $(git config remote.origin.url) in
```suggestion
			case $(git remote get-url origin) in
```
The value from config is not necessarily a URL, but gets translated to one by `url.*` configuration.

2019-07-17 12:47 UTC, tcely requested changes
- [x] use git remote
- [x] remove spaces in case matching

2019-07-23 04:58 UTC, tcely approved these changes

2019-07-23 05:02 UTC, tcely commented
You can rebase this and squash to a single commit to make it a bit cleaner.

2019-08-26 05:00 UTC, pdietl commented
Ok @tcely && @ncopa, I have rebased and squashed into one commit. Sorry for the delay. :p

2019-09-10 03:13 UTC, pdietl commented
@tcely @ncopa. Can we merge? :)

2019-09-30 10:36 UTC, closed without merging